// Generated by dart2js (NullSafetyMode.sound, csp, intern-composite-values), the Dart to JavaScript compiler version: 3.5.3.
((s, d, e) => {
  s[d] = s[d] || {};
  s[d][e] = s[d][e] || [];
  s[d][e].push({p: "main.clients.dart.js_3", e: "beginPart"});
})(self, "$__dart_deferred_initializers__", "eventLog");
$__dart_deferred_initializers__.current = function(hunkHelpers, init, holdersList, $) {
  var A,
  B = {
    EnumName_get_name(_this) {
      return _this._core$_name;
    }
  };
  A = holdersList[0];
  B = hunkHelpers.updateHolder(holdersList[11], B);
  var typesOffset = hunkHelpers.updateTypes([]);
  A._Universe_addRules(init.typeUniverse, JSON.parse('{"Widget":{"DiagnosticableTree":[],"_DiagnosticableTree_Object_Diagnosticable":[],"Diagnosticable":[]}}'));
};
;
((d, h) => {
  d[h] = d.current;
  d.eventLog.push({p: "main.clients.dart.js_3", e: "endPart", h: h});
})($__dart_deferred_initializers__, "QkgWMfDw3raDxgoGq7N3XONBBoU=");
;
//# sourceMappingURL=main.clients.dart.js_3.part.js.map
