// Generated by dart2js (NullSafetyMode.sound, csp, intern-composite-values), the Dart to JavaScript compiler version: 3.5.3.
((s, d, e) => {
  s[d] = s[d] || {};
  s[d][e] = s[d][e] || [];
  s[d][e].push({p: "main.clients.dart.js_9", e: "beginPart"});
})(self, "$__dart_deferred_initializers__", "eventLog");
$__dart_deferred_initializers__.current = function(hunkHelpers, init, holdersList, $) {
  var J, B, C, D,
  A = {
    UnitExt_get_px(_this) {
      return A._PixelsUnit$(C.JSNumber_methods.toDouble$0(_this));
    },
    _PixelsUnit$(value) {
      return new A._PixelsUnit("px", value);
    },
    NumberString_get_numstr(_this) {
      return B.boolConversionCheck(J.$eq$(C.JSNumber_methods.roundToDouble$0(_this), _this)) ? J.toString$0$(C.JSNumber_methods.round$0(_this)) : C.JSNumber_methods.toString$0(_this);
    },
    _Unit: function _Unit() {
    },
    _PixelsUnit: function _PixelsUnit(t0, t1) {
      this._unit = t0;
      this._unit$_value = t1;
    },
    _BoxStyles$(height, margin, maxHeight, maxWidth, minHeight, minWidth) {
      return new A._BoxStyles(margin, height, maxWidth, maxHeight, minWidth, minHeight);
    },
    _extension_0__prefixed(_this, prefix) {
      var t1 = type$.String;
      return _this.map$2$1(0, new A._extension_0__prefixed_closure(prefix), t1, t1);
    },
    _CombinedStyles$(_styles) {
      return new A._CombinedStyles(_styles);
    },
    _BoxStyles: function _BoxStyles(t0, t1, t2, t3, t4, t5) {
      var _ = this;
      _.margin = t0;
      _.height = t1;
      _.maxWidth = t2;
      _.maxHeight = t3;
      _.minWidth = t4;
      _.minHeight = t5;
    },
    _extension_0__prefixed_closure: function _extension_0__prefixed_closure(t0) {
      this.prefix = t0;
    },
    Styles: function Styles() {
    },
    StylesMixin: function StylesMixin() {
    },
    _CombinedStyles: function _CombinedStyles(t0) {
      this._styles = t0;
    },
    _CombinedStyles_styles_closure: function _CombinedStyles_styles_closure() {
    },
    _Styles_Object_StylesMixin: function _Styles_Object_StylesMixin() {
    },
    StatefulElement$(component) {
      var t1 = component.createState$0(),
        t2 = B.HashSet_HashSet(type$.Element),
        t3 = $.Element__nextHashCode;
      if (typeof t3 !== "number")
        return t3.$add();
      t3 = C.JSNumber_methods.$mod(t3 + 1, 16777215);
      $.Element__nextHashCode = t3;
      t3 = new A.StatefulElement(t1, t2, t3, component, C._ElementLifecycle_0);
      t3.StatefulElement$1(component);
      return t3;
    },
    StatefulComponent: function StatefulComponent() {
    },
    State: function State() {
    },
    StatefulElement: function StatefulElement(t0, t1, t2, t3, t4) {
      var _ = this;
      _._framework$_state = t0;
      _._asyncInitState = null;
      _._didChangeDependencies = false;
      _._children = null;
      _._forgottenChildren = t1;
      _._notificationTree = _._parent = null;
      _._cachedHash = t2;
      _._depth = null;
      _._component = t3;
      _._owner = _._binding = null;
      _._lifecycleState = t4;
      _._dependencies = _._inheritedElements = _._observerElements = null;
      _._hadUnsatisfiedDependencies = false;
      _._dirty = true;
      _._inDirtyList = false;
      _._lastRenderObjectElement = _._lastChild = _._prevAncestorSibling = _._prevSibling = _._parentRenderObjectElement = null;
      _._parentChanged = false;
    },
    StatefulElement_performRebuild_closure: function StatefulElement_performRebuild_closure(t0) {
      this.$this = t0;
    },
    div(children, classes, id, key, styles) {
      return D.DomComponent$(null, null, children, classes, null, id, key, styles, "div");
    }
  };
  J = holdersList[1];
  B = holdersList[0];
  C = holdersList[2];
  D = holdersList[10];
  A = hunkHelpers.updateHolder(holdersList[8], A);
  A._Unit.prototype = {
    get$value() {
      return B.S(A.NumberString_get_numstr(this._unit$_value)) + B.S(this._unit);
    },
    $eq(_, other) {
      var t1, t2, t3, t4, _this = this;
      if (other == null)
        return false;
      t1 = true;
      if (_this !== other) {
        t2 = _this._unit$_value;
        t3 = J.getInterceptor$(t2);
        if (B.boolConversionCheck(t3.$eq(t2, 0)))
          t4 = other instanceof A._Unit && B.boolConversionCheck(J.$eq$(other._unit$_value, 0));
        else
          t4 = false;
        if (!t4)
          t1 = other instanceof A._Unit && B.boolConversionCheck(J.$eq$(_this.get$runtimeType(0), other.get$runtimeType(0))) && B.boolConversionCheck(J.$eq$(_this._unit, other._unit)) && B.boolConversionCheck(t3.$eq(t2, other._unit$_value));
      }
      return t1;
    },
    get$hashCode(_) {
      var t3,
        t1 = this._unit$_value,
        t2 = J.getInterceptor$(t1);
      if (B.boolConversionCheck(t2.$eq(t1, 0)))
        t1 = 0;
      else {
        t3 = J.get$hashCode$(this._unit);
        t1 = t2.get$hashCode(t1);
        if (typeof t3 !== "number")
          return t3.$xor();
        if (typeof t1 !== "number")
          return B.iae(t1);
        t1 = (t3 ^ t1) >>> 0;
      }
      return t1;
    },
    $isUnit: 1
  };
  A._PixelsUnit.prototype = {};
  A._BoxStyles.prototype = {
    get$styles() {
      var t2, _this = this,
        t1 = type$.String;
      t1 = B.LinkedHashMap_LinkedHashMap$_empty(t1, t1);
      t2 = _this.margin;
      t2 = t2 == null ? null : A._extension_0__prefixed(t2.get$styles(), "margin");
      if (t2 != null)
        t1.addAll$1(0, t2);
      t2 = _this.height;
      if (t2 != null)
        t1.$indexSet(0, "height", t2.get$value());
      t2 = _this.minWidth;
      if (t2 != null)
        t1.$indexSet(0, "min-width", t2.get$value());
      t2 = _this.maxWidth;
      if (t2 != null)
        t1.$indexSet(0, "max-width", t2.get$value());
      t2 = _this.minHeight;
      if (t2 != null)
        t1.$indexSet(0, "min-height", t2.get$value());
      t2 = _this.maxHeight;
      if (t2 != null)
        t1.$indexSet(0, "max-height", t2.get$value());
      return t1;
    }
  };
  A.Styles.prototype = {$isStylesMixin: 1};
  A.StylesMixin.prototype = {};
  A._CombinedStyles.prototype = {
    get$styles() {
      var t1 = type$.String;
      return J.fold$1$2$ax(this._styles, B.LinkedHashMap_LinkedHashMap$_empty(t1, t1), new A._CombinedStyles_styles_closure(), type$.Map_String_String);
    }
  };
  A._Styles_Object_StylesMixin.prototype = {$isStylesMixin: 1};
  A.StatefulComponent.prototype = {
    createElement$0() {
      return A.StatefulElement$(this);
    }
  };
  A.State.prototype = {
    get$component() {
      var t1 = this._component;
      t1.toString;
      return t1;
    },
    get$context() {
      var t1 = this._framework$_element;
      t1.toString;
      return t1;
    },
    get$mounted() {
      return this._framework$_element != null;
    },
    initState$0() {
    },
    shouldRebuild$1(newComponent) {
      B._instanceType(this)._eval$1("State.T")._as(newComponent);
      return true;
    },
    didUpdateComponent$1(oldComponent) {
      B._instanceType(this)._eval$1("State.T")._as(oldComponent);
    },
    setState$1(fn) {
      type$.void_Function._as(fn).call$0();
      this._framework$_element.markNeedsBuild$0();
    },
    deactivate$0() {
    },
    dispose$0() {
    },
    didChangeDependencies$0() {
    },
    set$_component(_component) {
      this._component = B._instanceType(this)._eval$1("State.T?")._as(_component);
    }
  };
  A.StatefulElement.prototype = {
    StatefulElement$1(component) {
      this.get$state()._framework$_element = this;
      this.get$state().set$_component(component);
    },
    build$0() {
      return this.get$state().build$1(this);
    },
    get$state() {
      var t1 = this._framework$_state;
      t1.toString;
      return t1;
    },
    didMount$0() {
      var _this = this;
      if (B.boolConversionCheck(_this.get$owner().get$isFirstBuild()))
        _this.get$state();
      _this._initState$0();
      _this.super$BuildableElement$didMount();
    },
    _initState$0() {
      var _this = this;
      try {
        _this._debugSetAllowIgnoredCallsToMarkNeedsBuild$1(true);
        _this.get$state().initState$0();
      } finally {
        _this._debugSetAllowIgnoredCallsToMarkNeedsBuild$1(false);
      }
      _this.get$state().didChangeDependencies$0();
    },
    performRebuild$0() {
      var _this = this;
      if (B.boolConversionCheck(_this.get$owner().get$isFirstBuild()) && _this._asyncInitState != null)
        return _this._asyncInitState.then$1$1(new A.StatefulElement_performRebuild_closure(_this), type$.void);
      if (B.boolConversionCheck(_this._didChangeDependencies)) {
        _this.get$state().didChangeDependencies$0();
        _this._didChangeDependencies = false;
      }
      _this.super$BuildableElement$performRebuild();
    },
    shouldRebuild$1(newComponent) {
      type$.StatefulComponent._as(newComponent);
      return this.get$state().shouldRebuild$1(newComponent);
    },
    update$1(newComponent) {
      type$.StatefulComponent._as(newComponent);
      this.super$Element$update(newComponent);
      this.get$state().set$_component(newComponent);
    },
    didUpdate$1(oldComponent) {
      var _this = this;
      type$.StatefulComponent._as(oldComponent);
      try {
        _this._debugSetAllowIgnoredCallsToMarkNeedsBuild$1(true);
        _this.get$state().didUpdateComponent$1(oldComponent);
      } finally {
        _this._debugSetAllowIgnoredCallsToMarkNeedsBuild$1(false);
      }
      _this.super$Element$didUpdate(oldComponent);
    },
    deactivate$0() {
      this.get$state().deactivate$0();
      this.super$Element$deactivate();
    },
    unmount$0() {
      var _this = this;
      _this.super$Element$unmount0();
      _this.get$state().dispose$0();
      _this.get$state()._framework$_element = null;
      _this.set$_framework$_state(null);
    },
    set$_framework$_state(_state) {
      this._framework$_state = type$.nullable_State_StatefulComponent._as(_state);
    }
  };
  var typesOffset = hunkHelpers.updateTypes(["Map<String,String>(Map<String,String>,Styles)"]);
  A._extension_0__prefixed_closure.prototype = {
    call$2(k, v) {
      var t1, t2;
      B._asString(k);
      B._asString(v);
      t1 = B.boolConversionCheck(C.JSString_methods.get$isNotEmpty(k)) ? "-" + k : "";
      t2 = type$.String;
      return B.MapEntry$_(J.$add$ansx(this.prefix, t1), v, t2, t2);
    },
    $signature: 138
  };
  A._CombinedStyles_styles_closure.prototype = {
    call$2(v, s) {
      type$.Map_String_String._as(v);
      v.addAll$1(0, type$.Styles._as(s).get$styles());
      return v;
    },
    $signature: typesOffset + 0
  };
  A.StatefulElement_performRebuild_closure.prototype = {
    call$1(_) {
      var t1 = this.$this;
      if (B.boolConversionCheck(t1._didChangeDependencies)) {
        t1.get$state().didChangeDependencies$0();
        t1._didChangeDependencies = false;
      }
      t1.super$BuildableElement$performRebuild();
    },
    $signature: 2
  };
  (function aliases() {
    var _ = A.State.prototype;
    _.super$State$initState = _.initState$0;
    _.super$State$didUpdateComponent = _.didUpdateComponent$1;
    _.super$State$dispose0 = _.dispose$0;
  })();
  (function inheritance() {
    var _mixinHard = hunkHelpers.mixinHard,
      _inheritMany = hunkHelpers.inheritMany,
      _inherit = hunkHelpers.inherit;
    _inheritMany(B.Object, [A._Unit, A._Styles_Object_StylesMixin, A.StylesMixin, A.State]);
    _inherit(A._PixelsUnit, A._Unit);
    _inherit(A.Styles, A._Styles_Object_StylesMixin);
    _inheritMany(A.Styles, [A._BoxStyles, A._CombinedStyles]);
    _inheritMany(B.Closure2Args, [A._extension_0__prefixed_closure, A._CombinedStyles_styles_closure]);
    _inherit(A.StatefulComponent, B.Component);
    _inherit(A.StatefulElement, D.BuildableElement);
    _inherit(A.StatefulElement_performRebuild_closure, B.Closure);
    _mixinHard(A._Styles_Object_StylesMixin, A.StylesMixin);
  })();
  B._Universe_addRules(init.typeUniverse, JSON.parse('{"_ZeroUnit":{"Unit":[]},"_Unit":{"Unit":[]},"_PixelsUnit":{"_Unit":[],"Unit":[]},"_BoxStyles":{"Styles":[],"_Styles_Object_StylesMixin":[],"StylesMixin":["Styles"]},"_ListStyles":{"Styles":[],"_Styles_Object_StylesMixin":[],"StylesMixin":["Styles"]},"_CombinedStyles":{"Styles":[],"_Styles_Object_StylesMixin":[],"StylesMixin":["Styles"]},"_Styles_Object_StylesMixin":{"StylesMixin":["Styles"]},"Styles":{"_Styles_Object_StylesMixin":[],"StylesMixin":["Styles"]},"_StateLifecycle":{"_Enum":[],"Enum":[]},"PreloadStateMixin":{"State":["1"]},"StatefulElement":{"BuildableElement":[],"Element":[],"BuildContext0":[]},"StatefulComponent":{"Component":[]},"Display0":{"_Enum":[],"Enum":[]},"Visibility":{"_Enum":[],"Enum":[]},"BoxSizing":{"_Enum":[],"Enum":[]},"ListStyle":{"_Enum":[],"Enum":[]},"ListStylePosition":{"_Enum":[],"Enum":[]}}'));
  var type$ = {
    Element: B.findType("Element"),
    Map_String_String: B.findType("Map<String,String>"),
    StatefulComponent: B.findType("StatefulComponent"),
    String: B.findType("String"),
    Styles: B.findType("Styles"),
    nullable_State_StatefulComponent: B.findType("State<StatefulComponent>?"),
    void: B.findType("~"),
    void_Function: B.findType("~()")
  };
};
;
((d, h) => {
  d[h] = d.current;
  d.eventLog.push({p: "main.clients.dart.js_9", e: "endPart", h: h});
})($__dart_deferred_initializers__, "IqPGFR+1yhj1rzOOchkemHUKImk=");
;
//# sourceMappingURL=main.clients.dart.js_9.part.js.map
