// Generated by dart2js (NullSafetyMode.sound, csp, intern-composite-values), the Dart to JavaScript compiler version: 3.5.3.
((s, d, e) => {
  s[d] = s[d] || {};
  s[d][e] = s[d][e] || [];
  s[d][e].push({p: "main.clients.dart.js_12", e: "beginPart"});
})(self, "$__dart_deferred_initializers__", "eventLog");
$__dart_deferred_initializers__.current = function(hunkHelpers, init, holdersList, $) {
  var B, C,
  A = {
    About$() {
      return new A.About(null);
    },
    About: function About(t0) {
      this.key = t0;
    },
    h3(children) {
      var _null = null;
      return D.DomComponent$(_null, _null, children, _null, _null, _null, _null, _null, "h3");
    },
    ol(children) {
      var _null = null,
        t1 = type$.String,
        t2 = B.LinkedHashMap_LinkedHashMap$_empty(t1, t1);
      t1 = E.LinkedHashMap_LinkedHashMap$of(t2, t1, t1);
      return D.DomComponent$(t1, _null, children, _null, _null, _null, _null, _null, "ol");
    },
    li(children) {
      var _null = null,
        t1 = type$.String,
        t2 = B.LinkedHashMap_LinkedHashMap$_empty(t1, t1);
      t1 = E.LinkedHashMap_LinkedHashMap$of(t2, t1, t1);
      return D.DomComponent$(t1, _null, children, _null, _null, _null, _null, _null, "li");
    },
    a(children, href) {
      var _null = null,
        t1 = type$.String,
        t2 = B.LinkedHashMap_LinkedHashMap$_empty(t1, t1);
      t1 = E.LinkedHashMap_LinkedHashMap$of(t2, t1, t1);
      t1.$indexSet(0, "href", href);
      return D.DomComponent$(t1, _null, children, _null, _null, _null, _null, _null, "a");
    },
    getComponentForParams(p) {
      return A.About$();
    }
  },
  E, D;
  B = holdersList[0];
  C = holdersList[7];
  A = hunkHelpers.updateHolder(holdersList[4], A);
  E = holdersList[12];
  D = holdersList[10];
  A.About.prototype = {
    build$1(context) {
      return B._makeSyncStarIterable(this.build$body$About(type$.BuildContext._as(context)), type$.Component);
    },
    build$body$About($async$context) {
      return function() {
        var context = $async$context;
        var $async$goto = 0, $async$handler = 1, $async$currentError, t1;
        return function $async$build$1($async$iterator, $async$errorCode, $async$result) {
          if ($async$errorCode === 1) {
            $async$currentError = $async$result;
            $async$goto = $async$handler;
          }
          while (true)
            switch ($async$goto) {
              case 0:
                // Function start
                t1 = type$.JSArray_Component;
                $async$goto = 2;
                return $async$iterator._async$_current = C.section(B._setArrayType([A.ol(B._setArrayType([A.li(B._setArrayType([A.h3(B._setArrayType([C.text("\ud83d\udcd6 Documentation")], t1)), C.text("Jaspr's "), A.a(B._setArrayType([C.text("official documentation")], t1), "https://docs.page/schultek/jaspr"), C.text(" provides you with all information you need to get started.")], t1)), A.li(B._setArrayType([A.h3(B._setArrayType([C.text("\ud83d\udcac Community")], t1)), C.text("Got stuck? Ask your question on the official "), A.a(B._setArrayType([C.text("Discord server")], t1), "https://docs.page/schultek/jaspr"), C.text(" for the Jaspr community.")], t1)), A.li(B._setArrayType([A.h3(B._setArrayType([C.text("\ud83d\udce6 Ecosystem")], t1)), C.text("Get official packages and integrations for your project like jaspr_router, jaspr_tailwind or jaspr_riverpod. Find packages built for Jaspr on pub.dev using the "), A.a(B._setArrayType([C.text("#jaspr")], t1), "https://pub.dev/packages?q=topic%3Ajaspr"), C.text(" topic, or publish your own.")], t1)), A.li(B._setArrayType([A.h3(B._setArrayType([C.text("\ud83d\udc99 Support Jaspr")], t1)), C.text("If you like Jaspr, consider starring us on "), A.a(B._setArrayType([C.text("Github")], t1), "https://github.com/schultek/jaspr"), C.text(" and tell your friends.")], t1))], t1))], t1)), 1;
              case 2:
                // after yield
                // implicit return
                return 0;
              case 1:
                // rethrow
                return $async$iterator._datum = $async$currentError, 3;
            }
        };
      };
    }
  };
  var typesOffset = hunkHelpers.updateTypes([]);
  (function inheritance() {
    var _inherit = hunkHelpers.inherit;
    _inherit(A.About, C.StatelessComponent);
  })();
  B._Universe_addRules(init.typeUniverse, JSON.parse('{"About":{"StatelessComponent":[],"Component":[]},"NumberingType":{"_Enum":[],"Enum":[]},"Target":{"_Enum":[],"Enum":[]}}'));
  var type$ = {
    BuildContext: B.findType("BuildContext0"),
    Component: B.findType("Component"),
    JSArray_Component: B.findType("JSArray<Component>"),
    String: B.findType("String")
  };
};
;
((d, h) => {
  d[h] = d.current;
  d.eventLog.push({p: "main.clients.dart.js_12", e: "endPart", h: h});
})($__dart_deferred_initializers__, "5zua39MDTohyWNHGLVtF8DJ4c8U=");
;
//# sourceMappingURL=main.clients.dart.js_12.part.js.map
