// Generated by dart2js (NullSafetyMode.sound, csp, intern-composite-values), the Dart to JavaScript compiler version: 3.5.3.
((s, d, e) => {
  s[d] = s[d] || {};
  s[d][e] = s[d][e] || [];
  s[d][e].push({p: "main.clients.dart.js_8", e: "beginPart"});
})(self, "$__dart_deferred_initializers__", "eventLog");
$__dart_deferred_initializers__.current = function(hunkHelpers, init, holdersList, $) {
  var J, B, C, D,
  A = {
    HashMap_HashMap$from(other, $K, $V) {
      var result = D.HashMap_HashMap(null, null, null, $K, $V);
      other.forEach$1(0, new A.HashMap_HashMap$from_closure(result, $K, $V));
      return result;
    },
    HashMap_HashMap$from_closure: function HashMap_HashMap$from_closure(t0, t1, t2) {
      this.result = t0;
      this.K = t1;
      this.V = t2;
    },
    DomComponent$(attributes, child, children, classes, events, id, key, styles, tag) {
      return new A.DomComponent(tag, id, classes, styles, attributes, events, child, children, key);
    },
    DomElement$(component) {
      var t1 = B.HashSet_HashSet(type$.Element),
        t2 = $.Element__nextHashCode;
      if (typeof t2 !== "number")
        return t2.$add();
      t2 = C.JSNumber_methods.$mod(t2 + 1, 16777215);
      $.Element__nextHashCode = t2;
      return new A.DomElement(null, false, t1, t2, component, C._ElementLifecycle_0);
    },
    Text$(text) {
      return new A.Text(text, null);
    },
    TextElement$(component) {
      var t1 = $.Element__nextHashCode;
      if (typeof t1 !== "number")
        return t1.$add();
      t1 = C.JSNumber_methods.$mod(t1 + 1, 16777215);
      $.Element__nextHashCode = t1;
      return new A.TextElement(null, false, t1, component, C._ElementLifecycle_0);
    },
    BuildableElement: function BuildableElement() {
    },
    DomComponent: function DomComponent(t0, t1, t2, t3, t4, t5, t6, t7, t8) {
      var _ = this;
      _.tag = t0;
      _.id = t1;
      _.classes = t2;
      _.styles = t3;
      _.attributes = t4;
      _.events = t5;
      _.child = t6;
      _.children = t7;
      _.key = t8;
    },
    DomElement: function DomElement(t0, t1, t2, t3, t4, t5) {
      var _ = this;
      _._wrappingElement = null;
      _.RenderObjectElement__renderObject = t0;
      _.RenderObjectElement__dirtyRender = t1;
      _._children = null;
      _._forgottenChildren = t2;
      _._notificationTree = _._parent = null;
      _._cachedHash = t3;
      _._depth = null;
      _._component = t4;
      _._owner = _._binding = null;
      _._lifecycleState = t5;
      _._dependencies = _._inheritedElements = _._observerElements = null;
      _._hadUnsatisfiedDependencies = false;
      _._dirty = true;
      _._inDirtyList = false;
      _._lastRenderObjectElement = _._lastChild = _._prevAncestorSibling = _._prevSibling = _._parentRenderObjectElement = null;
      _._parentChanged = false;
    },
    DomElement_updateRenderObject_closure: function DomElement_updateRenderObject_closure() {
    },
    DomElement_updateRenderObject_closure0: function DomElement_updateRenderObject_closure0() {
    },
    DomElement_updateRenderObject_closure1: function DomElement_updateRenderObject_closure1() {
    },
    DomElement_updateRenderObject_closure2: function DomElement_updateRenderObject_closure2() {
    },
    Text: function Text(t0, t1) {
      this.text = t0;
      this.key = t1;
    },
    TextElement: function TextElement(t0, t1, t2, t3, t4) {
      var _ = this;
      _.RenderObjectElement__renderObject = t0;
      _.RenderObjectElement__dirtyRender = t1;
      _._notificationTree = _._parent = null;
      _._cachedHash = t2;
      _._depth = null;
      _._component = t3;
      _._owner = _._binding = null;
      _._lifecycleState = t4;
      _._dependencies = _._inheritedElements = _._observerElements = null;
      _._hadUnsatisfiedDependencies = false;
      _._dirty = true;
      _._inDirtyList = false;
      _._lastRenderObjectElement = _._lastChild = _._prevAncestorSibling = _._prevSibling = _._parentRenderObjectElement = null;
      _._parentChanged = false;
    },
    LeafElement: function LeafElement() {
    },
    LeafRenderObjectElement0: function LeafRenderObjectElement0() {
    }
  },
  E;
  J = holdersList[1];
  B = holdersList[0];
  C = holdersList[2];
  D = holdersList[12];
  A = hunkHelpers.updateHolder(holdersList[10], A);
  E = holdersList[17];
  A.BuildableElement.prototype = {
    mount$2($parent, prevSibling) {
      var t1 = type$.nullable_Element;
      this.super$Element$mount(t1._as($parent), t1._as(prevSibling));
    },
    didMount$0() {
      this.rebuild$0();
      this.super$Element$didMount();
    },
    shouldRebuild$1(newComponent) {
      type$.Component._as(newComponent);
      return true;
    },
    performRebuild$0() {
      var e, st, exception, t1, t2, _this = this, _null = null, built = null;
      try {
        built = J.toList$0$ax(_this.build$0());
      } catch (exception) {
        e = B.unwrapException(exception);
        st = B.getTraceFromException(exception);
        built = B._setArrayType([A.DomComponent$(_null, A.Text$("Error on building component: " + B.S(e)), _null, _null, _null, _null, _null, _null, "div")], type$.JSArray_Component);
        B.print("Error: " + B.S(e) + " " + B.S(st));
      } finally {
        _this._dirty = false;
      }
      t1 = _this._children;
      if (t1 == null)
        t1 = B._setArrayType([], type$.JSArray_Element);
      t2 = _this._forgottenChildren;
      _this.set$_children(_this.updateChildren$3$forgottenChildren(t1, built, t2));
      J.clear$0$ax(t2);
    },
    visitChildren$1(visitor) {
      var t1, t2, t3, t4, child;
      type$.void_Function_Element._as(visitor);
      t1 = this._children;
      t1 = J.get$iterator$ax(t1 == null ? [] : t1);
      t2 = this._forgottenChildren;
      t3 = J.getInterceptor$asx(t2);
      t4 = type$.Element;
      for (; B.boolConversionCheck(t1.moveNext$0());) {
        child = t1.get$current();
        if (!B.boolConversionCheck(t3.contains$1(t2, child)))
          visitor.call$1(t4._as(child));
      }
    },
    set$_children(_children) {
      this._children = type$.nullable_List_Element._as(_children);
    }
  };
  A.DomComponent.prototype = {
    createElement$0() {
      return A.DomElement$(this);
    }
  };
  A.DomElement.prototype = {
    get$component() {
      return type$.DomComponent._as(B.Element.prototype.get$component.call(this));
    },
    _updateInheritance$0() {
      var t1, _this = this;
      _this.super$Element$_updateInheritance();
      t1 = _this._inheritedElements;
      if (t1 != null && B.boolConversionCheck(t1.containsKey$1(E.Type__WrappingDomComponent_xw8))) {
        t1 = _this._inheritedElements;
        t1.toString;
        _this.set$_inheritedElements(A.HashMap_HashMap$from(t1, type$.Type, type$.InheritedElement));
      }
      t1 = _this._inheritedElements;
      _this.set$_wrappingElement(t1 == null ? null : J.remove$1$ax(t1, E.Type__WrappingDomComponent_xw8));
    },
    shouldRerender$1(newComponent) {
      var _this = this;
      type$.DomComponent._as(newComponent);
      return !B.boolConversionCheck(J.$eq$(_this.get$component().tag, newComponent.tag)) || !B.boolConversionCheck(J.$eq$(_this.get$component().id, newComponent.id)) || !B.boolConversionCheck(J.$eq$(_this.get$component().classes, newComponent.classes)) || !B.boolConversionCheck(J.$eq$(_this.get$component().styles, newComponent.styles)) || !B.boolConversionCheck(J.$eq$(_this.get$component().attributes, newComponent.attributes)) || !B.boolConversionCheck(J.$eq$(_this.get$component().events, newComponent.events));
    },
    updateRenderObject$0() {
      var wrappingComponent, t2, t3, t4, t5, t6, t7, _this = this,
        t1 = _this._wrappingElement;
      if (t1 != null) {
        wrappingComponent = type$._WrappingDomComponent._as(_this.dependOnInheritedElement$1(t1));
        t1 = _this.get$renderObject();
        t2 = _this.get$component().tag;
        t3 = _this.get$component().id;
        if (t3 == null)
          t3 = wrappingComponent.get$id();
        t4 = _this._join$1$3(wrappingComponent.get$classes(), _this.get$component().classes, new A.DomElement_updateRenderObject_closure(), type$.String);
        t5 = wrappingComponent.get$styles();
        t5 = t5 == null ? null : t5.get$styles();
        t6 = _this.get$component().styles;
        t6 = t6 == null ? null : t6.get$styles();
        t7 = type$.Map_String_String;
        t1.updateElement$6(t2, t3, t4, _this._join$1$3(t5, t6, new A.DomElement_updateRenderObject_closure0(), t7), _this._join$1$3(wrappingComponent.get$attributes(), _this.get$component().attributes, new A.DomElement_updateRenderObject_closure1(), t7), _this._join$1$3(wrappingComponent.get$events(), _this.get$component().events, new A.DomElement_updateRenderObject_closure2(), type$.Map_of_String_and_void_Function_JSObject));
        return;
      }
      t1 = _this.get$renderObject();
      t2 = _this.get$component().tag;
      t3 = _this.get$component().id;
      t4 = _this.get$component().classes;
      t5 = _this.get$component().styles;
      t5 = t5 == null ? null : t5.get$styles();
      t1.updateElement$6(t2, t3, t4, t5, _this.get$component().attributes, _this.get$component().events);
    },
    _join$1$3(a, b, joiner, $T) {
      var t1 = $T._eval$1("0?");
      t1._as(a);
      t1._as(b);
      $T._eval$1("0(0,0)")._as(joiner);
      t1 = a == null;
      if (!t1 && b != null)
        t1 = joiner.call$2(a, b);
      else
        t1 = t1 ? b : a;
      return t1;
    },
    set$_wrappingElement(_wrappingElement) {
      this._wrappingElement = type$.nullable_InheritedElement._as(_wrappingElement);
    }
  };
  A.Text.prototype = {
    createElement$0() {
      return A.TextElement$(this);
    }
  };
  A.TextElement.prototype = {
    shouldRerender$1(newComponent) {
      var t1 = type$.Text;
      t1._as(newComponent);
      return !B.boolConversionCheck(J.$eq$(t1._as(this.get$component()).text, newComponent.text));
    },
    updateRenderObject$0() {
      this.get$renderObject().updateText$1(type$.Text._as(this.get$component()).text);
    }
  };
  A.LeafElement.prototype = {
    mount$2($parent, prevSibling) {
      var t1 = type$.nullable_Element;
      this.super$Element$mount(t1._as($parent), t1._as(prevSibling));
    },
    didMount$0() {
      this.rebuild$0();
      this.super$Element$didMount();
    },
    shouldRebuild$1(newComponent) {
      type$.Component._as(newComponent);
      return false;
    },
    performRebuild$0() {
      this._dirty = false;
    },
    visitChildren$1(visitor) {
      type$.void_Function_Element._as(visitor);
    }
  };
  A.LeafRenderObjectElement0.prototype = {
    didMount$0() {
      var _this = this;
      if (_this.RenderObjectElement__renderObject == null) {
        _this.set$_renderObject(_this.createRenderObject$0());
        _this.updateRenderObject$0();
      }
      _this.super$LeafElement$didMount();
    },
    update$1(newComponent) {
      type$.Component._as(newComponent);
      if (B.boolConversionCheck(this.shouldRerender$1(newComponent)))
        this.RenderObjectElement__dirtyRender = true;
      this.super$Element$update(newComponent);
    },
    didUpdate$1(oldComponent) {
      var _this = this;
      type$.Component._as(oldComponent);
      if (B.boolConversionCheck(_this.RenderObjectElement__dirtyRender)) {
        _this.RenderObjectElement__dirtyRender = false;
        _this.updateRenderObject$0();
      }
      _this.super$Element$didUpdate(oldComponent);
    },
    _didUpdateSlot$0() {
      this.super$Element$_didUpdateSlot();
      this.attachRenderObject$0();
    },
    $isRenderObjectElement0: 1
  };
  var typesOffset = hunkHelpers.updateTypes([]);
  A.HashMap_HashMap$from_closure.prototype = {
    call$2(k, v) {
      J.$indexSet$ax(this.result, this.K._as(k), this.V._as(v));
    },
    $signature: 31
  };
  A.DomElement_updateRenderObject_closure.prototype = {
    call$2(a, b) {
      return B._asString(a) + " " + B._asString(b);
    },
    $signature: 134
  };
  A.DomElement_updateRenderObject_closure0.prototype = {
    call$2(a, b) {
      var t1 = type$.Map_String_String;
      t1._as(a);
      t1._as(b);
      t1 = type$.String;
      t1 = D.LinkedHashMap_LinkedHashMap$of(a, t1, t1);
      t1.addAll$1(0, b);
      return t1;
    },
    $signature: 63
  };
  A.DomElement_updateRenderObject_closure1.prototype = {
    call$2(a, b) {
      var t1 = type$.Map_String_String;
      t1._as(a);
      t1._as(b);
      t1 = type$.String;
      t1 = D.LinkedHashMap_LinkedHashMap$of(a, t1, t1);
      t1.addAll$1(0, b);
      return t1;
    },
    $signature: 63
  };
  A.DomElement_updateRenderObject_closure2.prototype = {
    call$2(a, b) {
      var t1 = type$.Map_of_String_and_void_Function_JSObject;
      t1._as(a);
      t1._as(b);
      t1 = D.LinkedHashMap_LinkedHashMap$of(a, type$.String, type$.void_Function_JSObject);
      t1.addAll$1(0, b);
      return t1;
    },
    $signature: 136
  };
  (function aliases() {
    var _ = A.BuildableElement.prototype;
    _.super$BuildableElement$didMount = _.didMount$0;
    _.super$BuildableElement$performRebuild = _.performRebuild$0;
    _ = A.LeafElement.prototype;
    _.super$LeafElement$didMount = _.didMount$0;
  })();
  (function inheritance() {
    var _mixinHard = hunkHelpers.mixinHard,
      _inheritMany = hunkHelpers.inheritMany,
      _inherit = hunkHelpers.inherit;
    _inheritMany(B.Closure2Args, [A.HashMap_HashMap$from_closure, A.DomElement_updateRenderObject_closure, A.DomElement_updateRenderObject_closure0, A.DomElement_updateRenderObject_closure1, A.DomElement_updateRenderObject_closure2]);
    _inheritMany(B.Element, [A.BuildableElement, A.LeafElement]);
    _inherit(A.DomComponent, B.ProxyComponent);
    _inherit(A.DomElement, B.ProxyRenderObjectElement);
    _inherit(A.Text, B.Component);
    _inherit(A.LeafRenderObjectElement0, A.LeafElement);
    _inherit(A.TextElement, A.LeafRenderObjectElement0);
    _mixinHard(A.LeafRenderObjectElement0, B.RenderObjectElement0);
  })();
  B._Universe_addRules(init.typeUniverse, JSON.parse('{"BuildableElement":{"Element":[],"BuildContext0":[]},"DomComponent":{"ProxyComponent":[],"Component":[]},"DomElement":{"ProxyRenderObjectElement":[],"ProxyElement":[],"RenderObjectElement0":[],"Element":[],"BuildContext0":[]},"_WrappingDomComponent":{"InheritedComponent":[],"DomComponent":[],"ProxyComponent":[],"Component":[]},"Text":{"Component":[]},"TextElement":{"LeafRenderObjectElement0":[],"LeafElement":[],"RenderObjectElement0":[],"Element":[],"BuildContext0":[]},"LeafElement":{"Element":[],"BuildContext0":[]},"LeafRenderObjectElement0":{"LeafElement":[],"RenderObjectElement0":[],"Element":[],"BuildContext0":[]},"Styles":{"_Styles_Object_StylesMixin":[],"StylesMixin":["Styles"]}}'));
  var type$ = (function rtii() {
    var findType = B.findType;
    return {
      Component: findType("Component"),
      DomComponent: findType("DomComponent"),
      Element: findType("Element"),
      InheritedElement: findType("InheritedElement0"),
      JSArray_Component: findType("JSArray<Component>"),
      JSArray_Element: findType("JSArray<Element>"),
      Map_String_String: findType("Map<String,String>"),
      Map_of_String_and_void_Function_JSObject: findType("Map<String,~(JSObject)>"),
      String: findType("String"),
      Text: findType("Text"),
      Type: findType("Type"),
      _WrappingDomComponent: findType("_WrappingDomComponent"),
      nullable_Element: findType("Element?"),
      nullable_InheritedElement: findType("InheritedElement0?"),
      nullable_List_Element: findType("List<Element>?"),
      void_Function_Element: findType("~(Element)"),
      void_Function_JSObject: findType("~(JSObject)")
    };
  })();
  (function constants() {
    E.Type__WrappingDomComponent_xw8 = B.typeLiteral("_WrappingDomComponent");
  })();
};
;
((d, h) => {
  d[h] = d.current;
  d.eventLog.push({p: "main.clients.dart.js_8", e: "endPart", h: h});
})($__dart_deferred_initializers__, "2144RCB66Gw9H/bTjblcc2xFgYE=");
;
//# sourceMappingURL=main.clients.dart.js_8.part.js.map
