// Generated by dart2js (NullSafetyMode.sound, csp, intern-composite-values), the Dart to JavaScript compiler version: 3.5.3.
((s, d, e) => {
  s[d] = s[d] || {};
  s[d][e] = s[d][e] || [];
  s[d][e].push({p: "main.clients.dart.js_11", e: "beginPart"});
})(self, "$__dart_deferred_initializers__", "eventLog");
$__dart_deferred_initializers__.current = function(hunkHelpers, init, holdersList, $) {
  var B, D,
  A = {
    StatelessElement$(component) {
      var t1 = B.HashSet_HashSet(type$.Element),
        t2 = $.Element__nextHashCode;
      if (typeof t2 !== "number")
        return t2.$add();
      t2 = D.JSNumber_methods.$mod(t2 + 1, 16777215);
      $.Element__nextHashCode = t2;
      return new A.StatelessElement(t1, t2, component, D._ElementLifecycle_0);
    },
    StatelessComponent: function StatelessComponent() {
    },
    StatelessElement: function StatelessElement(t0, t1, t2, t3) {
      var _ = this;
      _._children = _._asyncFirstBuild = null;
      _._forgottenChildren = t0;
      _._notificationTree = _._parent = null;
      _._cachedHash = t1;
      _._depth = null;
      _._component = t2;
      _._owner = _._binding = null;
      _._lifecycleState = t3;
      _._dependencies = _._inheritedElements = _._observerElements = null;
      _._hadUnsatisfiedDependencies = false;
      _._dirty = true;
      _._inDirtyList = false;
      _._lastRenderObjectElement = _._lastChild = _._prevAncestorSibling = _._prevSibling = _._parentRenderObjectElement = null;
      _._parentChanged = false;
    },
    StatelessElement_performRebuild_closure: function StatelessElement_performRebuild_closure(t0) {
      this.$this = t0;
    },
    section(children) {
      var _null = null;
      return C.DomComponent$(_null, _null, children, _null, _null, _null, _null, _null, "section");
    },
    text(text) {
      return C.Text$(text);
    }
  },
  C;
  B = holdersList[0];
  D = holdersList[2];
  A = hunkHelpers.updateHolder(holdersList[7], A);
  C = holdersList[10];
  A.StatelessComponent.prototype = {
    createElement$0() {
      return A.StatelessElement$(this);
    },
    shouldRebuild$1(newComponent) {
      type$.Component._as(newComponent);
      return true;
    }
  };
  A.StatelessElement.prototype = {
    get$component() {
      return type$.StatelessComponent._as(B.Element.prototype.get$component.call(this));
    },
    didMount$0() {
      var _this = this;
      if (B.boolConversionCheck(_this.get$owner().get$isFirstBuild()))
        if (!B.boolConversionCheck(_this.get$binding().get$isClient()))
          _this.get$component();
      _this.super$BuildableElement$didMount();
    },
    shouldRebuild$1(newComponent) {
      type$.Component._as(newComponent);
      return this.get$component().shouldRebuild$1(newComponent);
    },
    build$0() {
      return this.get$component().build$1(this);
    },
    performRebuild$0() {
      var _this = this;
      if (B.boolConversionCheck(_this.get$owner().get$isFirstBuild()) && _this._asyncFirstBuild != null)
        return _this._asyncFirstBuild.then$1$1(new A.StatelessElement_performRebuild_closure(_this), type$.void);
      _this.super$BuildableElement$performRebuild();
    }
  };
  var typesOffset = hunkHelpers.updateTypes([]);
  A.StatelessElement_performRebuild_closure.prototype = {
    call$1(_) {
      this.$this.super$BuildableElement$performRebuild();
    },
    $signature: 2
  };
  (function inheritance() {
    var _inherit = hunkHelpers.inherit;
    _inherit(A.StatelessComponent, B.Component);
    _inherit(A.StatelessElement, C.BuildableElement);
    _inherit(A.StatelessElement_performRebuild_closure, B.Closure);
  })();
  B._Universe_addRules(init.typeUniverse, JSON.parse('{"StatelessComponent":{"Component":[]},"OnFirstBuild":{"StatelessComponent":[],"Component":[]},"StatelessElement":{"BuildableElement":[],"Element":[],"BuildContext0":[]},"ReferrerPolicy":{"_Enum":[],"Enum":[]}}'));
  var type$ = {
    Component: B.findType("Component"),
    Element: B.findType("Element"),
    StatelessComponent: B.findType("StatelessComponent"),
    void: B.findType("~")
  };
};
;
((d, h) => {
  d[h] = d.current;
  d.eventLog.push({p: "main.clients.dart.js_11", e: "endPart", h: h});
})($__dart_deferred_initializers__, "WuEpah88r24KKRYLjkHFZFmAjhg=");
;
//# sourceMappingURL=main.clients.dart.js_11.part.js.map
